package com.atlasscans.android.data.models

import kotlinx.serialization.Serializable

/**
 * 3-D coordinate in metres, right-handed (ARCore native convention).
 * Matches the spatial coordinate format required by AtlasContracts.
 */
@Serializable
data class SpatialCoordinate(
    val x: Float,
    val y: Float,
    val z: Float,
)

/**
 * A single detected plane (floor, ceiling, or wall) captured during the AR scan.
 */
@Serializable
data class DetectedPlane(
    /** Unique identifier for this plane. */
    val id: String,
    /**
     * Plane orientation type:
     * - "HORIZONTAL_UP"   – floor-like surface (normal pointing up)
     * - "HORIZONTAL_DOWN" – ceiling-like surface (normal pointing down)
     * - "VERTICAL"        – wall-like surface
     */
    val type: String,
    /** World-space centre of the plane polygon. */
    val centerPose: SpatialCoordinate,
    /** Half-extent along the plane's local X axis (metres). */
    val extentX: Float,
    /** Half-extent along the plane's local Z axis (metres). */
    val extentZ: Float,
)

/**
 * Full room-scan payload produced by the ARCore Depth API + plane detection.
 * Mirrors Apple's RoomPlan CapturedRoom for AtlasContracts binary compatibility.
 */
@Serializable
data class CapturedRoomScanV2(
    /** Unique identifier (UUID v4). */
    val id: String,
    /** Unix epoch milliseconds at scan completion. */
    val timestamp: Long,
    /**
     * Sampled point cloud in world space (metres).
     * Points are down-sampled to at most MAX_POINT_CLOUD_SIZE entries.
     */
    val pointCloud: List<SpatialCoordinate>,
    /** All planes tracked during the scan. */
    val detectedPlanes: List<DetectedPlane>,
    /** How long the user actively scanned (seconds). */
    val scanDurationSeconds: Float,
)

/**
 * A single high-resolution photo with optional spatial pin metadata.
 */
@Serializable
data class CapturedPhotoV2(
    /** Unique identifier (UUID v4). */
    val id: String,
    /** Absolute path on device storage. Excluded from the export bundle. */
    val filePath: String,
    /** Unix epoch milliseconds when the photo was taken. */
    val timestamp: Long,
    /**
     * ARCore hit-test coordinate where the pin was dropped, or null if
     * the photo was taken without a spatial anchor.
     */
    val coordinate: SpatialCoordinate?,
    /** Optional human-readable label for the pin. */
    val pinLabel: String?,
)

/**
 * A voice note.  The raw audio file is intentionally excluded from the
 * export bundle – only the transcript string is included, matching the iOS contract.
 */
@Serializable
data class VoiceNoteV2(
    /** Unique identifier (UUID v4). */
    val id: String,
    /** Speech-to-text transcript generated by Google SpeechRecognizer. */
    val transcript: String,
    /** Unix epoch milliseconds when recording started. */
    val timestamp: Long,
    /** Duration of the recording in seconds. */
    val durationSeconds: Float,
)

/**
 * Top-level capture session – the root object serialised and exported
 * as the JSON bundle consumed by Atlas Mind.
 */
@Serializable
data class SessionCaptureV2(
    /** Unique identifier (UUID v4). */
    val id: String,
    /** Unix epoch milliseconds when the session was created. */
    val createdAt: Long,
    /** The room scan, or null if scanning was not performed. */
    val roomScan: CapturedRoomScanV2?,
    /** All photos captured during the session. */
    val photos: List<CapturedPhotoV2>,
    /** All voice notes captured during the session. */
    val voiceNotes: List<VoiceNoteV2>,
)
